const { query, pool } = require('../../config/db');

const daysAgo = (days) =>
    new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

const hoursFromNow = (hours) =>
    new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();

const pexelsImage = (photoId) =>
    `https://images.pexels.com/photos/${photoId}/pexels-photo-${photoId}.jpeg?auto=compress&cs=tinysrgb&w=1200`;

function makeListing(
    id,
    sellerId,
    title,
    description,
    price,
    categoryId,
    condition,
    location,
    daysOld,
    options = {},
) {
    return {
        id,
        sellerId,
        title,
        description,
        price,
        currency: 'EUR',
        categoryId,
        condition,
        location,
        type: options.type || 'fixed',
        status: options.status || 'active',
        favoritesCount: options.favoritesCount || 0,
        viewsCount: options.viewsCount || 0,
        startingBid: options.startingBid || null,
        currentBid: null,
        bidsCount: 0,
        endsAt: options.endsAt || null,
        createdAt: daysAgo(daysOld),
        images: options.images || [],
    };
}

const listings = [
    // u1 — You
    makeListing(
        'l1',
        'u1',
        'Standing desk, electric',
        'Electric standing desk with adjustable height and memory controls. Minor signs of use.',
        240,
        'furniture',
        'very_good',
        'Lisbon',
        1,
        {
            favoritesCount: 2,
            viewsCount: 84,
            images: [pexelsImage(1957477)],
        },
    ),
    makeListing(
        'l2',
        'u1',
        '4K monitor, 27 inch',
        '27-inch 4K IPS monitor with HDMI and DisplayPort. Includes the original stand and power cable.',
        180,
        'electronics',
        'good',
        'Lisbon',
        3,
        {
            favoritesCount: 1,
            viewsCount: 63,
            images: [pexelsImage(1714208)],
        },
    ),
    makeListing(
        'l3',
        'u1',
        'Acoustic guitar with soft case',
        'Full-size acoustic guitar with a padded soft case. Recently fitted with new strings.',
        110,
        'home',
        'good',
        'Lisbon',
        5,
        {
            type: 'auction',
            startingBid: 60,
            endsAt: hoursFromNow(48),
            favoritesCount: 2,
            viewsCount: 91,
            images: [pexelsImage(164936)],
        },
    ),
    makeListing(
        'l4',
        'u1',
        'Bookshelf, white, 5 shelves',
        'White wooden bookshelf with five shelves. Stable and in good condition.',
        45,
        'furniture',
        'good',
        'Lisbon',
        8,
        {
            favoritesCount: 1,
            viewsCount: 37,
            images: [pexelsImage(1090638)],
        },
    ),
    makeListing(
        'l5',
        'u1',
        'Wireless headphones',
        'Over-ear Bluetooth headphones with active noise cancellation and carrying case.',
        75,
        'electronics',
        'like_new',
        'Lisbon',
        2,
        {
            favoritesCount: 2,
            viewsCount: 102,
            images: [pexelsImage(3394650)],
        },
    ),
    makeListing(
        'l6',
        'u1',
        'Coffee table, solid wood',
        'Solid wood coffee table with a natural finish. A few small marks on the surface.',
        65,
        'furniture',
        'good',
        'Lisbon',
        12,
        {
            status: 'sold',
            favoritesCount: 2,
            viewsCount: 76,
            images: [pexelsImage(276528)],
        },
    ),
    makeListing(
        'l7',
        'u1',
        'Set of classic novels',
        'Collection of twelve classic novels in English. All books are clean and complete.',
        35,
        'books',
        'very_good',
        'Lisbon',
        4,
        {
            favoritesCount: 1,
            viewsCount: 29,
            images: [pexelsImage(256450)],
        },
    ),
    makeListing(
        'l8',
        'u1',
        'Indoor plant with ceramic pot',
        'Healthy indoor plant supplied with a white ceramic pot. Easy to maintain.',
        25,
        'home',
        'like_new',
        'Lisbon',
        6,
        {
            favoritesCount: 2,
            viewsCount: 48,
            images: [pexelsImage(6208086)],
        },
    ),
    makeListing(
        'l9',
        'u1',
        'Adjustable dumbbell set',
        'Pair of adjustable dumbbells with weight plates. Suitable for home workouts.',
        90,
        'sports',
        'good',
        'Lisbon',
        7,
        {
            type: 'auction',
            startingBid: 40,
            endsAt: hoursFromNow(72),
            favoritesCount: 2,
            viewsCount: 88,
            images: [pexelsImage(416717)],
        },
    ),
    makeListing(
        'l10',
        'u1',
        'Vintage desk lamp',
        'Metal desk lamp with an adjustable arm. Tested and working correctly.',
        30,
        'home',
        'good',
        'Lisbon',
        15,
        {
            status: 'draft',
            images: [pexelsImage(1112598)],
        },
    ),

    // u2 — Marta Silva
    makeListing(
        'l11',
        'u2',
        'Vintage road bike, 54cm frame',
        'Steel-frame road bike with new brake pads and cables. Suitable for riders around 1.70–1.80m.',
        220,
        'bikes',
        'good',
        'Porto',
        1,
        {
            favoritesCount: 2,
            viewsCount: 145,
            images: [pexelsImage(100582)],
        },
    ),
    makeListing(
        'l12',
        'u2',
        'Oak dining table with 4 chairs',
        'Solid oak dining table supplied with four matching chairs. Collection in Porto.',
        180,
        'furniture',
        'good',
        'Porto',
        4,
        {
            favoritesCount: 2,
            viewsCount: 93,
            images: [pexelsImage(1571460)],
        },
    ),
    makeListing(
        'l13',
        'u2',
        'Wool winter coat, size M',
        'Warm wool coat in size M. Used only a few times and professionally cleaned.',
        55,
        'fashion',
        'like_new',
        'Porto',
        3,
        {
            favoritesCount: 1,
            viewsCount: 64,
            images: [pexelsImage(298863)],
        },
    ),
    makeListing(
        'l14',
        'u2',
        'Espresso coffee machine',
        'Espresso machine with milk frother. Recently descaled and working perfectly.',
        95,
        'home',
        'very_good',
        'Porto',
        2,
        {
            type: 'auction',
            startingBid: 45,
            endsAt: hoursFromNow(24),
            favoritesCount: 2,
            viewsCount: 127,
            images: [pexelsImage(302899)],
        },
    ),
    makeListing(
        'l15',
        'u2',
        'Leather handbag',
        'Brown leather handbag with adjustable shoulder strap and several internal compartments.',
        60,
        'fashion',
        'very_good',
        'Porto',
        6,
        {
            favoritesCount: 1,
            viewsCount: 52,
            images: [pexelsImage(1152077)],
        },
    ),
    makeListing(
        'l16',
        'u2',
        'Kids wooden train set',
        'Wooden train set with tracks, bridge, station and several train pieces.',
        35,
        'kids',
        'good',
        'Porto',
        9,
        {
            favoritesCount: 2,
            viewsCount: 71,
            images: [pexelsImage(207891)],
        },
    ),
    makeListing(
        'l17',
        'u2',
        'Box of science-fiction books',
        'Box containing twenty science-fiction paperbacks. Sold together as one collection.',
        30,
        'books',
        'good',
        'Porto',
        5,
        {
            favoritesCount: 1,
            viewsCount: 42,
            images: [pexelsImage(590493)],
        },
    ),
    makeListing(
        'l18',
        'u2',
        'Running shoes, size 39',
        'Lightweight running shoes in size 39. Clean and with very little sole wear.',
        40,
        'fashion',
        'very_good',
        'Porto',
        7,
        {
            favoritesCount: 1,
            viewsCount: 58,
            images: [pexelsImage(2529148)],
        },
    ),
    makeListing(
        'l19',
        'u2',
        'Two-person camping tent',
        'Water-resistant two-person camping tent. Includes poles, pegs and carrying bag.',
        70,
        'sports',
        'good',
        'Porto',
        11,
        {
            status: 'sold',
            favoritesCount: 2,
            viewsCount: 81,
            images: [pexelsImage(1687845)],
        },
    ),
    makeListing(
        'l20',
        'u2',
        'Baby stroller',
        'Foldable baby stroller with storage basket and rain cover.',
        85,
        'kids',
        'good',
        'Porto',
        14,
        {
            status: 'draft',
            images: [pexelsImage(3661350)],
        },
    ),

    // u3 — Tomas Reis
    makeListing(
        'l21',
        'u3',
        'iPhone 12, 128GB, unlocked',
        'Unlocked iPhone 12 with 128GB storage. Includes protective case and charging cable.',
        320,
        'electronics',
        'very_good',
        'Lisbon',
        2,
        {
            favoritesCount: 2,
            viewsCount: 178,
            images: [pexelsImage(788946)],
        },
    ),
    makeListing(
        'l22',
        'u3',
        'Mechanical keyboard, hot-swap',
        'Compact mechanical keyboard with hot-swappable switches and RGB lighting.',
        70,
        'electronics',
        'like_new',
        'Lisbon',
        1,
        {
            type: 'auction',
            startingBid: 30,
            endsAt: hoursFromNow(36),
            favoritesCount: 2,
            viewsCount: 116,
            images: [pexelsImage(2115257)],
        },
    ),
    makeListing(
        'l23',
        'u3',
        'City bicycle with basket',
        'Comfortable city bicycle with front basket, lights and rear rack.',
        160,
        'bikes',
        'good',
        'Lisbon',
        4,
        {
            favoritesCount: 2,
            viewsCount: 101,
            images: [pexelsImage(276517)],
        },
    ),
    makeListing(
        'l24',
        'u3',
        'Laptop, 16GB RAM, 512GB SSD',
        'Fast laptop with 16GB RAM and 512GB SSD. Battery and charger are in good condition.',
        520,
        'electronics',
        'very_good',
        'Lisbon',
        3,
        {
            favoritesCount: 2,
            viewsCount: 154,
            images: [pexelsImage(205421)],
        },
    ),
    makeListing(
        'l25',
        'u3',
        'Mountain bike helmet',
        'Lightweight mountain bike helmet with adjustable fit and removable padding.',
        45,
        'bikes',
        'like_new',
        'Lisbon',
        5,
        {
            favoritesCount: 1,
            viewsCount: 47,
            images: [pexelsImage(1640777)],
        },
    ),
    makeListing(
        'l26',
        'u3',
        'Football training set',
        'Training football with a set of cones and a compact carrying bag.',
        35,
        'sports',
        'good',
        'Lisbon',
        8,
        {
            favoritesCount: 1,
            viewsCount: 39,
            images: [pexelsImage(1263349)],
        },
    ),
    makeListing(
        'l27',
        'u3',
        'Wooden building blocks',
        'Colourful wooden building blocks for children. Complete set in original storage box.',
        25,
        'kids',
        'very_good',
        'Lisbon',
        6,
        {
            favoritesCount: 2,
            viewsCount: 55,
            images: [pexelsImage(3933025)],
        },
    ),
    makeListing(
        'l28',
        'u3',
        'Grey fabric sofa',
        'Three-seat grey fabric sofa with removable cushions. No stains or tears.',
        260,
        'furniture',
        'good',
        'Lisbon',
        10,
        {
            status: 'sold',
            favoritesCount: 2,
            viewsCount: 132,
            images: [pexelsImage(1866149)],
        },
    ),
    makeListing(
        'l29',
        'u3',
        'Digital camera with lens',
        'Digital camera with standard zoom lens, battery, charger and camera bag.',
        290,
        'electronics',
        'very_good',
        'Lisbon',
        7,
        {
            type: 'auction',
            startingBid: 150,
            endsAt: hoursFromNow(60),
            favoritesCount: 2,
            viewsCount: 143,
            images: [pexelsImage(90946)],
        },
    ),
    makeListing(
        'l30',
        'u3',
        'Modern floor lamp',
        'Minimalist floor lamp with metal base and fabric shade. Bulb included.',
        50,
        'home',
        'like_new',
        'Lisbon',
        13,
        {
            status: 'draft',
            images: [pexelsImage(112811)],
        },
    ),
];

async function seedListing(listing) {
    await query(
        `INSERT INTO listings (
			id,
			seller_id,
			title,
			description,
			price,
			currency,
			category_id,
			condition,
			location,
			type,
			status,
			favorites_count,
			views_count,
			starting_bid,
			current_bid,
			bids_count,
			ends_at,
			created_at
		)
		VALUES (
			$1, $2, $3, $4, $5, $6, $7, $8, $9,
			$10, $11, $12, $13, $14, $15, $16, $17, $18
		)
		ON CONFLICT (id) DO UPDATE SET
			seller_id = EXCLUDED.seller_id,
			title = EXCLUDED.title,
			description = EXCLUDED.description,
			price = EXCLUDED.price,
			currency = EXCLUDED.currency,
			category_id = EXCLUDED.category_id,
			condition = EXCLUDED.condition,
			location = EXCLUDED.location,
			type = EXCLUDED.type,
			status = EXCLUDED.status,
			favorites_count = EXCLUDED.favorites_count,
			views_count = EXCLUDED.views_count,
			starting_bid = EXCLUDED.starting_bid,
			current_bid = EXCLUDED.current_bid,
			bids_count = EXCLUDED.bids_count,
			ends_at = EXCLUDED.ends_at,
			created_at = EXCLUDED.created_at,
			updated_at = NOW()`,
        [
            listing.id,
            listing.sellerId,
            listing.title,
            listing.description,
            listing.price,
            listing.currency,
            listing.categoryId,
            listing.condition,
            listing.location,
            listing.type,
            listing.status,
            listing.favoritesCount,
            listing.viewsCount,
            listing.startingBid,
            listing.currentBid,
            listing.bidsCount,
            listing.endsAt,
            listing.createdAt,
        ],
    );

    /*
     * Remove as imagens anteriores deste anúncio antes de inserir o conjunto
     * atual. Isto impede imagens antigas ou duplicadas ao repetir o seed.
     */
    await query(
        `DELETE FROM listing_images
		 WHERE listing_id = $1`,
        [listing.id],
    );

    for (const [position, imageUrl] of listing.images.entries()) {
        await query(
            `INSERT INTO listing_images (
				id,
				listing_id,
				image_url,
				position
			)
			VALUES ($1, $2, $3, $4)`,
            [
                `${listing.id}_image_${position + 1}`,
                listing.id,
                imageUrl,
                position,
            ],
        );
    }
}

async function seedListingsTable() {
    for (const listing of listings) {
        await seedListing(listing);
        console.log(`Seeded listing ${listing.id}: ${listing.title}`);
    }

    console.log('Listings seed completed.');
}

seedListingsTable()
    .catch((error) => {
        console.error('Listings seed failed:', error);
        process.exitCode = 1;
    })
    .finally(() => pool.end());